title: Sarah Pullman
description: "The website of Sarah Pullman, an architectural studies major at Hobart and William Smith Colleges"

url: http://sarahpullman.github.io
# baseurl: ""
# paginate_path: "blog/page:num/"
# permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

sass:
   sass_dir: _sass
   style: :compressed

navigation:
 - title: About
   url: /
 - title: Contact
   url: /contact/

social:
   github: sarahpullman
   email: sspullman@gmail.com